### ISSUE TITLE
Remove horizontal scrollbar from website

### ISSUE THREAD

**Issue by drpotato** [windelicato/windelicato.github.io#1]
The bar at the top of the page is causing a horizontal scroll bar to be show, this annoyed me so I fixed found a fix.

In your style.css, change the bar id styling to:

``` css
#bar{
        position:absolute;
        top: 0px;
        left: 0px;
        background-color: #181512;
        color: #8c644c;
        box-shadow: 0px 5px 10px #181512;
        text-align: center;
        width: 100%;
        padding-top: 2px;
}
```

Just changing the padding of the bar to be on all four side to just the top, does not affect any other elements of the webpage.
